### ISSUE TITLE
validate_numeric() and friends are deprecated in stdlib

### ISSUE THREAD

**Issue by Flupsy** [voxpupuli/puppet-snmp#111]
The validate_*() functions in puppetlabs-stdlib have all been deprecated.  See https://github.com/puppetlabs/puppetlabs-stdlib#functions for details.

**Comment by khaefeli** [comment]
should be easy to replace. see the warning messages:

    Warning: This method is deprecated, please use the stdlib validate_legacy function, with Stdlib::Compat::Array. There is further documentation for validate_legacy function in the README.

**Comment by alexjfisher** [comment]
These are all fixed now.
