### ISSUE TITLE
Deprecate razorsedge/snmp

### ISSUE THREAD

**Issue by binford2k** [voxpupuli/puppet-snmp#163]
I've filed the ticket to deprecate the Forge module. @razorsedge, could you comment approval on it?

https://tickets.puppetlabs.com/browse/FORGE-466

**Comment by Dan33l** [comment]
Hi @razorsedge to avoid duplicate packages on the forge, can you consider to depracate the module under `razorsedge` name space ? Simply let a comment here to approve it.

**Comment by razorsedge** [comment]
Yes, please deprecate `razorsedge-snmp`.

**Comment by binford2k** [comment]
Thanks!
