### ISSUE TITLE
suggestion about ro_community removal planned in 5.0

### ISSUE THREAD

**Issue by hartmel** [voxpupuli/puppet-snmp#170]
Hello
I have noticed the expected removal of ro_community in favor of the VACM model for the 5.0 release and I'd like to speak in favor of keeping this setting. These post probably reflects a subjective point of view, but I ll try to be fair. 

For what I saw on many snmpd setups, setting the community with a source restricted to a /32 host address (or even restricted to a dedicated management prefix) provides enough security.
Multiple sources are well managed by adding lines for the same SNMP community, as it s done with array arguments in the current 4.0 version. The per-view access control is a very fine grained tool but often, simple RO access to the root tree is OK.
I often saw setups with iptables used to restrict access rather than the VACM configuration model.

It keep configuration files clear and easy to debug, and integration in external/custom ENCs is very easy.
Currently, the rocommunity/rwcommunity settings in snmpd.conf is not deprecated in the net-snmp project.

Personally, I find the complexity of VACM isn't worth the benefit it could bring. As time flows, SNMP monitoring needs on hosts will probably lose some market shares, being replaced by "higher level" protocols and custom agents, thus I think that keeping this module simple to use and the opportunity to use the simple security model is a good thing.

Thanks for reading, and please feel free to comment.

**Comment by alexjfisher** [comment]
@hartmel Thank you for the feedback.  The feature was originally scheduled for removal in version 4.0.0, but we pushed this back as we hadn't got a strong consensus on whether we should actually go through with it.

The feature was deprecated 4 years ago by the module's author in this [commit](https://github.com/voxpupuli/puppet-snmp/commit/84bab501f58c9b3fcd474fdd224d3c485e930e12).

Also see this PR comment [thread](https://github.com/voxpupuli/puppet-snmp/pull/139#issuecomment-433501018) where @trevor-vaughan also wants the feature to remain.

@razorsedge Was there a specific reason you wanted to remove the feature?

**Comment by alexjfisher** [comment]
FWIW, the official net-snmp documentation doesn't deprecate the feature, but does use the heading '[Living in Denial](http://net-snmp.sourceforge.net/wiki/index.php?title=Vacm&oldid=5863#Living_in_Denial)' ;)

**Comment by trevor-vaughan** [comment]
@alexjfisher I 100% agree with the Living in Denial part. However, when IT stops living in denial, it'll be a great day everywhere (hasn't happened yet).

**Comment by ghoneycutt** [comment]
We shouldn't remove the existing functionality. If new functionality is needed, please submit a PR. Thanks for your input everyone!

**Comment by alexjfisher** [comment]
We should update the readme and include the undeprecating in the 5.0 changelog release summary.
