### ISSUE TITLE
Dependancy listings are out of date

### ISSUE THREAD

**Issue by thaylin** [voxpupuli/puppet-snmp#178]
The stdlib version listed as a dependancy is not accurate. It lists 4.13, I started with 4.14, however it did not work.
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.10.12
- Ruby: 2.5.1p57
- Distribution: Rhel 7
- Module version: latest, stdlib 4.14

## How to reproduce (e.g Puppet code you use)
Set stdlib < 4.22
## What are you seeing
Resource type Stdlib::Ensure::Service does not exist This resource was not added until 4.22.
## What behaviour did you expect instead
The module to work

**Comment by bastelfreak** [comment]
@thaylin thanks for rising up this issue. Can you provide a PR that updates the metadata.json?
