### ISSUE TITLE
remove hardcoded group 'root'

### ISSUE THREAD

**Issue by decibelhertz** [voxpupuli/puppet-snmp#206]
Please allow user control of owner and especially group for files in the class declarations. The GID 0 is `root` on Linux, but `wheel` on FreeBD, OS X etc.  I'd like to be able to use this module across multiple kernels, and others may wish to control this for client and service.

E.G. https://github.com/voxpupuli/puppet-snmp/blob/v4.1.0/manifests/client.pp#L61

Further, are you planning on dropping support for FreeBSD?  The master branch appears to have done this.

Cheers.

**Comment by geoffdavis** [comment]
> Further, are you planning on dropping support for FreeBSD? The master branch appears to have done this.

They sure did, and it's sure annoying. Trying to put it back.

**Comment by geoffdavis** [comment]
Looks like the group problem was fixed in a partial conversion to module hieradata in GH-181
