### ISSUE TITLE
$facts['networking']['fqdn'] is too recent

### ISSUE THREAD

**Issue by alaunay** [voxpupuli/puppet-snmp#222]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6
- Module version: 5.0.0

Beginning from 5.0.0, sysname is defined as $facts['networking']['fqdn'] . Trouble is, only the most recent Debian has the possibility to use that syntax. The older Jessie (8) and Stretch (9) don't have it. Would it be possible to go back to the $::fqdn syntax, which works absolutely everywhere ? Or to have some kind of mechanism trying the $facts stuff, and going back to the direct fqdn is not found ?

Thanks.

**Comment by silug** [comment]
Puppet 6 is EOL and was dropped in module version 7.0.0.  The legacy facts are no longer supported in Puppet 8.

I know this is an old issue, but if you are still stuck on an EOL Puppet release, your best bet is to pin to an older version of the module.

**Comment by alaunay** [comment]
Which is what we did... Unfortunately, we still have a bunch of old Debian with even old puppet agents. We'll do a puppet-legacy server for those, and a puppet-modern for the others, starting with Debian 12 / bookworm.

Thanks for the consideration, even if it's a bit late ;-)

**Comment by kenyon** [comment]
@alaunay you can use multiple puppet environments on the same puppet server, each environment (== branch of the control repo) having different versions of modules. That'd be better/easier than multiple puppet servers.
