### ISSUE TITLE
Docs: Incorrect dependency (stdlib) listed on forge.puppet.com page

### ISSUE THREAD

**Issue by syl-nktaylor** [voxpupuli/puppet-snmp#227]
## What are you seeing

On https://forge.puppet.com/puppet/snmp/dependencies , for versions 5.1.0 and 5.0.0:

"puppetlabs/stdlib (>= 4.25.0 < 7.0.0)" is incorrect

## What behaviour did you expect instead

"puppetlabs/stdlib (>= 5.2.0 < 7.0.0)"

## Any additional information you'd like to impart

module snmp versions >= 5.0.0 use "Stdlib::IP::Address::V6::CIDR" which was created in module stdlib version 5.2.0

Related: https://github.com/voxpupuli/puppet-snmp/issues/224

Is it possible to update the information listed in forge.puppet.com?

**Comment by alexjfisher** [comment]
I'll make a new release.  See https://github.com/voxpupuli/puppet-snmp/pull/228

**Comment by alexjfisher** [comment]
5.1.1 is now released to the forge
