### ISSUE TITLE
Doesn't work on ubuntu focal 20.04

### ISSUE THREAD

**Issue by trunet** [voxpupuli/puppet-snmp#229]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6.16.0
- Ruby: 2.7.0
- Distribution: Ubuntu 20.04
- Module version: 5.1.0

## How to reproduce (e.g Puppet code you use)
```
class { 'snmp':
  agentaddress => [ 'udp:161', 'udp6:161' ],
}
```

## What are you seeing
Errors, see Output log below

## What behaviour did you expect instead
Deploys successfully without errors

## Output log
```
Error: Could not find user snmp
Error: /Stage[main]/Snmp/File[var-net-snmp]/owner: change from 'Debian-snmp' to 'snmp' failed: Could not find user snmp
Error: Could not find group snmp
Error: /Stage[main]/Snmp/File[var-net-snmp]/group: change from 'Debian-snmp' to 'snmp' failed: Could not find group snmp
Notice: /Stage[main]/Nrpe/Package[nagios-plugins]/ensure: created (corrective)
Notice: /Stage[main]/Snmp/Service[snmptrapd]: Dependency File[var-net-snmp] has failures: true
Warning: /Stage[main]/Snmp/Service[snmptrapd]: Skipping because of failed dependencies
Warning: /Stage[main]/Snmp/Service[snmpd]: Skipping because of failed dependencies
```

## Any additional information you'd like to impart
Looks like there a pull request already on https://github.com/voxpupuli/puppet-snmp/pull/226. Would be nice to have this verified and merged. I can see 3 tests failing there.

**Comment by aaroneg** [comment]
Assuming that you have a case statement for ubuntu 20.04 already, you can use this to call the snmp class without it breaking based on my quick testing:
```
        snmpd_options            => '-Lsd -Lf /dev/null -u Debian-snmp -g Debian-snmp -I -smux -p /var/run/snmpd.pid',
        service_config_dir_group => 'Debian-snmp',
        service_config_dir_owner => 'Debian-snmp',
        varnetsnmp_owner         => 'Debian-snmp',
        varnetsnmp_group         => 'Debian-snmp',
```
I used the diff from #226 to compose this. 
Tested on `mod 'puppet-snmp', '5.1.1'`
At some point in the future you should be able to drop these extra lines without consequence.
