### ISSUE TITLE
Support Debian Bullseye 11 (to be released in may or june)

### ISSUE THREAD

**Issue by eLvErDe** [voxpupuli/puppet-snmp#243]
Hello,

Could you add support for this new Debian stable release and publish and uppdated module ?

Adding support is rather trivial:

```
cp data/os/Debian/10.yaml data/os/Debian/11.yaml
```

Thanks a lot !

**Comment by jdelker** [comment]
With Debian "Bullseye" 11 released, this becomes critical now!

**Comment by ghoneycutt** [comment]
Vox Pupuli is a community effort. Please send a pull request with the changes above along with the `README.md` (https://github.com/voxpupuli/puppet-snmp/blob/master/README.md#limitations) and `metadata.json` (https://github.com/voxpupuli/puppet-snmp/blob/master/metadata.json#L51).

Please be sure the options from Debian 10 are actually the default options in Debian 11 found in `/etc/sysconfig/snmpd`.

**Comment by kenyon** [comment]
Yes, tests fail and there's a review comment that needs to be addressed.
