### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by mcarrolle** [voxpupuli/puppet-snmp#261]
Hi,

Can you release a new version with the Debian 11 changes?

**Comment by sboyd-m** [comment]
Gonna be *that guy* and add a vote
It's always a bit uncomfortable pointing our Puppetfile to a commit rather than a nice tidy version

6.0.1 seems like it would be fine?

**Comment by cfeskens** [comment]
Ditto this for RHEL9 support.

**Comment by kenyon** [comment]
See https://voxpupuli.org/docs/releasing_version/ for instructions on creating a release pull request.

**Comment by zilchms** [comment]
should be ok now with #282
