### ISSUE TITLE
Support for Ubuntu 22.04

### ISSUE THREAD

**Issue by Conzar** [voxpupuli/puppet-snmp#263]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: All
- Ruby: All
- Distribution: Ubuntu 22.04
- Module version: All

## How to reproduce (e.g Puppet code you use)
Use Ubuntu 22.04 in a VM and use snmp class.

## What are you seeing

```
    default: Error: Could not find user snmp
    default: Error: /Stage[main]/Snmp/File[var-net-snmp]/owner: change from 'Debian-snmp' to 'snmp' failed: Could not find user snmp
    default: Error: Could not find group snmp
    default: Error: /Stage[main]/Snmp/File[var-net-snmp]/group: change from 'Debian-snmp' to 'snmp' failed: Could not find group snmp
```

## What behaviour did you expect instead

snmp to install correctly

## Output log
See error above

**Comment by Conzar** [comment]
This is fixed in the master branch

**Comment by PenguinFreeDom** [comment]
Are you sure this is fixed ?....i am still seeing this error on version 6.0.0

**Comment by Conzar** [comment]
> Are you sure this is fixed ?....i am still seeing this error on version 6.0.0

It is fixed in the master branch.  So whenever they release a new version to puppet forge, it will be fixed there too.

**Comment by prouveyrol** [comment]
Hello.
I'm here, just shy of a year later, and while I found that [this PR](https://github.com/voxpupuli/puppet-snmp/pull/268) is indeed merged into master and not a part of 6.0.0, I'm left wondering why no version bump happened yet. Anything we can do to help?

**Comment by kenyon** [comment]
@prouveyrol mostly someone just needs to make a release pull request. See https://voxpupuli.org/docs/releasing_version/. Also #261.

**Comment by prouveyrol** [comment]
@kenyon oh, I didn't know how the voxpopuli modules worked. My apologies. I'll see if I can have a go at it then.
