### ISSUE TITLE
Are v3 user auth/priv password changes supported?

### ISSUE THREAD

**Issue by baron1405** [voxpupuli/puppet-snmp#4]
Looking through the snmpv3_user define, it does not appear that a change to the user's authentication or privacy passwords will be realized in the snmp configuration. It appears that the presence of the user is detected but not the credentials. Granted net-snmp makes this difficult and would requiring deriving the localized key for comparison on the usmUser line.

**Comment by Seegras** [comment]
I checked out the module, but can't find any reference to snmpusm (which happens to be in the package "snmp" on a modern Debian/Ubuntu, and which isn't installed by the module). So how exactly is the module even supposed to create users?

**Comment by Seegras** [comment]
Got it. ran into this: https://bugs.launchpad.net/ubuntu/+source/net-snmp/+bug/1322431 
There's still a problem: the module does not install libsnmp-dev which is supposed to include /usr/bin/net-snmp-create-v3-user
