### ISSUE TITLE
Provide a higher-level interface to snmpd

### ISSUE THREAD

**Issue by tlimoncelli** [voxpupuli/puppet-snmp#54]
Most sites have simple needs that can be stated at a high level as:
- read only:
  - "communitystring1", [list of cidr blocks]
  - "communitystring2", [list of cidr blocks]
- read/write::
  - "communitystring3", [list of cidr blocks]
  - "communitystring4", [list of cidr blocks]

I propose a snmp::easy{} class that simply takes those values and generates the appropriate class parameters to snmp{}.

[Note: This will be super easy to implement in Puppet 4, but will make the module unusable by people that still use Puppet 3.x.  When my site upgrades to Puppet 4, I'll be glad to contribute code.]

**Comment by razorsedge** [comment]
If I keep `ro_community` and friends around and if #49 gets merged, will this solve the issue?

I have been debating about creating a Define['snmp::config'] that will piece together the snmpd.conf instead of fitting everything into one monolithic template.

**Comment by tlimoncelli** [comment]
Yes, that'd be great!

My though with ::easy() (a terrible name, but you might have a better one) is that it would be high-level enough that it could configure some other snmp package.  That is, if someone wrote something better than net-snmp, the ::easy() class would do the right thing.

**Comment by razorsedge** [comment]
Hindsight being 20/20, I really wish that I had named several of my modules differently.  This module is one of them.  I should have named it razorsedge-netsnmp.

In a perfect world, I might have a razorsedge-snmp module that is a wrapper around a razorsedge-netsnmp module and a razorsedge-aixsnmp module.  Then I could just call the wrapper `::snmp` module with the generic parameters and have the different platforms do-the-right-thing(TM).

**Comment by TomOnTime** [comment]
That happens to us all.

**Comment by ghoneycutt** [comment]
Closing as this issue is quite old.
