### ISSUE TITLE
Disable snmp v2 & v1

### ISSUE THREAD

**Issue by hdep** [voxpupuli/puppet-snmp#56]
Hello,

I am currently testing your plugin which seems working fine on my system (debian 8).
Il only want to use snmpv3, this is working but the plugin is still generating some configuration about snmp v2, is there a way to disable this ? 

Regards,

**Comment by razorsedge** [comment]
@hdep I am not positive, but try this:
```puppet
class { 'snmp':
  ro_community  => undef,
  ro_community6 => undef,
  groups         => [ 'myGroupName v3         mySecName', ],
}
```

**Comment by tarheeljeff** [comment]
Any updated comments on disabling v1/v2 as part of the config?

**Comment by msiroskey** [comment]
After looking into the code you can disable v1/v2 by passing an empty array to com2sec and com2sec6 parameters.

```
class { 'snmp':
  com2sec      => [],
  com2sec6     => [],
}
```

**Comment by razorsedge** [comment]
Looks like a documentation update is in order.

**Comment by hdep** [comment]
Thank you.
Juste tried that on Debain 9 I got some error :  

Aug  9 16:49:39 serversnmpd[12025]: /etc/snmp/snmpd.conf: line 22: Error: Blank line following com2sec token.
Aug  9 16:49:39 server snmpd[12025]: /etc/snmp/snmpd.conf: line 24: Error: Blank line following com2sec6 token.

Maybe it would more efficient to create a variable which enable or disable snmpv2 configuration ?

**Comment by hdep** [comment]
I did a PR for this : 
https://github.com/razorsedge/puppet-snmp/pull/128

Any help appreciated to fix the remaining issue, but it is working on my VM.
