### ISSUE TITLE
Guidance using this module

### ISSUE THREAD

**Issue by linuxphone** [voxpupuli/puppet-snmp#64]
Team,
Can someone provide me with some guidance in getting this module to work. I am using RHEL 7 and puppet 3.8. Thank you.

**Comment by razorsedge** [comment]
@linuxphone 
From the README:

> **Beginning with this module**
> 
> This declaration will get you the SNMP daemon listening on the loopback IPv4 and IPv6 addresses with a v1 and v2c read-only community of 'public'.
> ```puppet
> include ::snmp
> ```

Beyond that, we would have to know what you were trying to do.

**Comment by vStone** [comment]
2 year old question. not a bug.
