### ISSUE TITLE
RFC-standard MIBS on Debian / Ubuntu

### ISSUE THREAD

**Issue by tolecnal** [voxpupuli/puppet-snmp#66]
Hello,

I saw you had an item listed as an issue in your README, pertaining to RFC-standard MIBS on Debian. If you install the package 'snmp-mibs-downloader' and uncomment the following line in /etc/snmp/snmp.conf:

mibs :

You should now be able to do 'snmpwalk -v 2c -c public localhost system'

This package is available in the following versions of Debian:
- wheezy
- jessie
- sid

Please not however that the package is in the 'non-free' section for Debian packages, and in the 'Multiverse' section for Ubuntu packages.

**Comment by razorsedge** [comment]
This is a duplicate of #16. 
I probably will not get around to fixing this without a PR.

**Comment by Dan33l** [comment]
closed because of duplicate.
comments will be done on #16
