### ISSUE TITLE
can't change value of snmp_com2sec (and potentially some other variables)

### ISSUE THREAD

**Issue by MaDYeTTi** [voxpupuli/puppet-snmp#72]
I've tried t change value of snmp_com2sec to something like "notConfigUser  127.0.0.1     public".

Problem is that's not passing check_array.
So effectively you can't change it to a string you need.

here is error log:

> Error: Could not retrieve catalog from remote server: Error 400 on SERVER: "notConfigUser  127.0.0.1     public" is not an Array.  It looks to be a String at /etc/puppet/_blah-blah-blah_/snmp/manifests/init.pp:319 on node test

Maybe it's not a best idea to use check_array for some of these variables.

**Comment by razorsedge** [comment]
@MaDYeTTi check_array is doing it's job.  Try setting the value to an array:

```
snmp_com2sec = ['notConfigUser 127.0.0.1 public']
```

**Comment by vStone** [comment]
Looks like this is not really a bug. Data typing has been put in place.
