### ISSUE TITLE
rouser in snmpd.conf missing for v3 auth

### ISSUE THREAD

**Issue by hostingnuggets** [voxpupuli/puppet-snmp#9]
Hi,

I am currently testing this module with Debian 7 and SNMP v3 auth, unfortunately it does not work as it does not add the "rouser" parameter into the snmpd.conf file. Here is my puppet manifest:

class { 'snmp':
  agentaddress => [ 'udp:161', ],
  contact      => 'root@yourdomain.org',
  location     => 'Phoenix, AZ',
}

snmp::snmpv3_user { 'myv3user':
  authpass => 'authpass',
  privpass => 'privpass',
}

This should actually add the "rouser myv3user" line to snmpd.conf but it doesn't. As such I get the following problem:

$ snmpwalk -v3 -u myv3user -l authNoPriv -a SHA -A authpass -X privpass localhost

Error in packet.
Reason: authorizationError (access denied to that object)

Let me know if you need more details!
Thanks

**Comment by srianirudh84** [comment]
Hi @linuxmail  

Just curious, were you able to get it to work ?

**Comment by linuxmail** [comment]
hi @srianirudh84 

nope, I just put the command into a exec script :-/

**Comment by Dan33l** [comment]
We can consider this issue as resolved.
